// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAvaliacaoDeProfissionais.Models;

#nullable disable

namespace SistemaAvaliacaoDeProfissionais.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220504014744_atualizacaoBanco1")]
    partial class atualizacaoBanco1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Cargo", b =>
                {
                    b.Property<int>("CargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoID"), 1L, 1);

                    b.Property<string>("NomeCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoCargoID")
                        .HasColumnType("int");

                    b.HasKey("CargoID");

                    b.HasIndex("TipoCargoID");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Gestores", b =>
                {
                    b.Property<int>("GestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GestorID"), 1L, 1);

                    b.Property<int>("ProfissionalID")
                        .HasColumnType("int");

                    b.HasKey("GestorID");

                    b.HasIndex("ProfissionalID")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.PeriodoAvaliacao", b =>
                {
                    b.Property<int>("PeriodoAvaliacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodoAvaliacaoID"), 1L, 1);

                    b.Property<bool>("AvaliacaoExpirada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataExpiracaoAutoAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpiracaoAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioAutoAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Liberada")
                        .HasColumnType("bit");

                    b.Property<int>("PeriodoID")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalID")
                        .HasColumnType("int");

                    b.HasKey("PeriodoAvaliacaoID");

                    b.HasIndex("PeriodoID");

                    b.HasIndex("ProfissionalID");

                    b.ToTable("PeriodosAvaliacao");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Periodos", b =>
                {
                    b.Property<int>("PeriodoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodoID"), 1L, 1);

                    b.Property<int>("CodigoPeriodo")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeriodoID");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.PlanoDeAcao", b =>
                {
                    b.Property<int>("PlanoDeAcaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanoDeAcaoID"), 1L, 1);

                    b.Property<string>("ConsideracoesDoColaboradorAvaliado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsideracoesFinaisDosPlanosDeAcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoID")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalID")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoDaAcaoProposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoPlanoDeAcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoQuestao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanoDeAcaoID");

                    b.HasIndex("PeriodoID");

                    b.HasIndex("ProfissionalID");

                    b.ToTable("PlanosDeAcao");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Profissionais", b =>
                {
                    b.Property<int>("ProfissionalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfissionalID"), 1L, 1);

                    b.Property<DateTime>("Admissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("CargoID")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetorID")
                        .HasColumnType("int");

                    b.Property<int>("StatusAvaliacaoID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfissionalID");

                    b.HasIndex("CargoID");

                    b.HasIndex("SetorID");

                    b.HasIndex("StatusAvaliacaoID");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Questionario", b =>
                {
                    b.Property<int>("QuestaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestaoID"), 1L, 1);

                    b.Property<string>("Questao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoCargoID")
                        .HasColumnType("int");

                    b.Property<string>("TituloQuestao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestaoID");

                    b.HasIndex("TipoCargoID");

                    b.ToTable("Questionarios");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.RegistroDeAdvertencias", b =>
                {
                    b.Property<int>("RegistroDeAdvertenciasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroDeAdvertenciasID"), 1L, 1);

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAdvertencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoAvaliacaoID")
                        .HasColumnType("int");

                    b.HasKey("RegistroDeAdvertenciasID");

                    b.HasIndex("PeriodoAvaliacaoID");

                    b.ToTable("RegistroDeAdvertencias");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.ResultadoAvaliacao", b =>
                {
                    b.Property<int>("ResultadoAvaliacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultadoAvaliacaoID"), 1L, 1);

                    b.Property<DateTime?>("DataAutoAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GestorID")
                        .HasColumnType("int");

                    b.Property<double?>("NotaAutoAvaliacao")
                        .HasColumnType("float");

                    b.Property<double?>("NotaAvaliacao")
                        .HasColumnType("float");

                    b.Property<int>("PeriodoID")
                        .HasColumnType("int");

                    b.Property<int>("ProfissionalID")
                        .HasColumnType("int");

                    b.Property<string>("RespostasAutoAvaliacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespostasAvaliacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultadoAvaliacaoID");

                    b.HasIndex("GestorID");

                    b.HasIndex("PeriodoID");

                    b.HasIndex("ProfissionalID");

                    b.ToTable("ResultadoAvaliacoes");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Setores", b =>
                {
                    b.Property<int>("SetorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetorID"), 1L, 1);

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetorID");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.StatusAvaliacao", b =>
                {
                    b.Property<int>("StatusAvaliacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusAvaliacaoID"), 1L, 1);

                    b.Property<string>("NomeStatusAvaliacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusAvaliacaoID");

                    b.ToTable("StatusAvaliacoes");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.TipoCargo", b =>
                {
                    b.Property<int>("TipoCargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCargoID"), 1L, 1);

                    b.Property<string>("NomeTipoCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoCargoID");

                    b.ToTable("TipoCargos");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.UsuariosExclusivos", b =>
                {
                    b.Property<int>("UsuarioExclusivoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioExclusivoID"), 1L, 1);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioExclusivoID");

                    b.ToTable("UsuariosExclusivos");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Cargo", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.TipoCargo", "TipoCargo")
                        .WithMany()
                        .HasForeignKey("TipoCargoID");

                    b.Navigation("TipoCargo");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Gestores", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Profissionais", "Profissional")
                        .WithOne("Gestor")
                        .HasForeignKey("SistemaAvaliacaoDeProfissionais.Models.Gestores", "ProfissionalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.PeriodoAvaliacao", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Periodos", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Profissionais", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodo");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.PlanoDeAcao", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Periodos", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Profissionais", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodo");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Profissionais", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Setores", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.StatusAvaliacao", "StatusAvaliacao")
                        .WithMany()
                        .HasForeignKey("StatusAvaliacaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Setor");

                    b.Navigation("StatusAvaliacao");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Questionario", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.TipoCargo", "TipoCargo")
                        .WithMany()
                        .HasForeignKey("TipoCargoID");

                    b.Navigation("TipoCargo");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.RegistroDeAdvertencias", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.PeriodoAvaliacao", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoAvaliacaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.ResultadoAvaliacao", b =>
                {
                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Gestores", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorID");

                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Periodos", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAvaliacaoDeProfissionais.Models.Profissionais", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Periodo");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("SistemaAvaliacaoDeProfissionais.Models.Profissionais", b =>
                {
                    b.Navigation("Gestor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
